import 'package:flutter/material.dart';

List<Map<String, dynamic>> profiles = [
  {
    "id": 1,
    "image": "assets/images/p1.jpg",
    "name": "Livia",
    "msg": "Lorem Ipsum is simply dummy.",
    "time": "9:16PM",
    "mno": 1,
    "date": "Just now",
    "icons": Icons.call_made,
    "icons2": Icons.video_camera_back,
  },
  {
    "id": 2,
    "image": "assets/images/p2.jpg",
    "name": "Thanu",
    "msg": "Lorem Ipsum is simply dummy.",
    "time": "today",
    "mno": 1,
    "date": "4 minutes ago",
    "icons": Icons.call_received,
    "icons2": Icons.phone,
  },
  {
    "id": 3,
    "image": "assets/images/p3.jpg",
    "name": "Elza",
    "msg": "Lorem Ipsum is simply dummy.",
    "time": "yesterday",
    "mno": 1,
    "date": "January 28, 6:02 PM",
    "icons": Icons.call_received,
    "icons2": Icons.phone,
  },
  {
    "id": 4,
    "image": "assets/images/p4.jpg",
    "name": "Sali",
    "msg": "Lorem Ipsum is simply dummy.",
    "time": "Yesterday",
    "mno": 1,
    "date": "January 5, 9:45 AM",
    "icons": Icons.call_received,
    "icons2": Icons.video_camera_back,
  },
  {
    "id": 5,
    "image": "assets/images/p5.jpg",
    "name": "Oliver",
    "msg": "Lorem Ipsum is simply dummy.",
    "time": "Yesterday",
    "mno": 1,
    "date": "12/2/2023, 9:32 AM",
    "icons": Icons.call_made,
    "icons2": Icons.video_camera_back,
  },
  {
    "id": 6,
    "image": "assets/images/p6.jpg",
    "name": "Tony",
    "msg": "Lorem Ipsum is simply dummy.",
    "time": "Yesterday",
    "mno": 1,
    "date": "11/17/2023, 12:44 PM",
    "icons": Icons.call_received,
    "icons2": Icons.phone,
  },
  {
    "id": 7,
    "image": "assets/images/p7.jpg",
    "name": "Andrew",
    "msg": "Lorem Ipsum is simply dummy.",
    "time": "yesterday",
    "mno": 1,
    "date": "11/16/2023, 6:02PM",
    "icons": Icons.call_received,
    "icons2": Icons.video_camera_back,
  },
  {
    "id": 8,
    "image": "assets/images/p8.jpg",
    "name": "Jenny",
    "msg": "Lorem Ipsum is simply dummy.",
    "time": "1/26/24",
    "mno": 1,
    "date": "9/15/2023, 5:46 PM",
    "icons": Icons.call_received,
    "icons2": Icons.video_camera_back,
  },
  {
    "id": 9,
    "image": "assets/images/p9.jpg",
    "name": "Sandra",
    "msg": "Lorem Ipsum is simply dummy.",
    "time": "1/25/24",
    "mno": 1,
    "date": "8/15/2023, 3:52 PM",
    "icons": Icons.call_made,
    "icons2": Icons.video_camera_back,
  },
  {
    "id": 10,
    "image": "assets/images/p10.jpg",
    "name": "Lucas",
    "msg": "Lorem Ipsum is simply dummy.",
    "time": "1/15/24",
    "mno": 1,
    "date": "7/19/2023, 7:54PM",
    "icons": Icons.call_received,
    "icons2": Icons.phone,
  },
  {
    "id": 11,
    "image": "assets/images/p11.jpg",
    "name": "Zoya",
    "msg": "Lorem Ipsum is simply dummy.",
    "time": "1/4/2023",
    "mno": 1,
    "date": "7/15/2023, 7:54PM",
    "icons": Icons.call_received,
    "icons2": Icons.video_camera_back,
  },
  {
    "id": 12,
    "image": "assets/images/p12.jpg",
    "name": "Jeremy",
    "msg": "Lorem Ipsum is simply dummy.",
    "time": "12/19/2023",
    "mno": 1,
    "date": "7/15/2023, 8:54PM",
    "icons": Icons.call_received,
    "icons2": Icons.phone,
  }
];